### ISSUE TITLE
Question to select specific region by changing text inputs

### ISSUE THREAD

**Issue by YeongHyeon** [HealthX-Lab/MedCLIP-SAMv2#1]
Thank you for sharing this wonderful work!

I am trying to follow this project with Colab demo.
(I also take a process to set up to use this project on GPU cluster.)

By the way, I just entered the prompt of 'normal' status but it shows strong saliency on a tumor.
This is nice to suspect the regions as malignant tissues.
However, if the saliency regions are changed into normal region depending on 'normal' prompt, it will be better for my purpose.

Can I ask for your support in selecting normal regions by changing text inputs?

Thank you once more and hope you are always well.

**Comment by YeongHyeon** [comment]
<img width="653" alt="7 54 37" src="https://github.com/user-attachments/assets/67e654c1-321f-470a-bf7e-1ae34bbc4127">

**Comment by pdx1028** [comment]
你好，我想请问下你复现出来了吗？想问数据集准备那里，我感觉不太理解怎么操作，你能具体跟我描述一下吗？谢谢。

**Comment by YeongHyeon** [comment]
@pdx1028 Hi!

**Comment by pdx1028** [comment]
hi



---- Replied Message ----
| From | YeongHyeon ***@***.***> |
| Date | 10/11/2024 12:52 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [HealthX-Lab/MedCLIP-SAMv2] Question to select specific region by changing text inputs (Issue #1) |

@pdx1028 Hi!

**Comment by TahaKoleilat** [comment]
Hi @YeongHyeon,

Thank you for your interest in our work.

This will heavily depend on the inputted text prompts. As highlighted by the text saliency map, there is high attention to the word "tumor" in your input text prompt. I suggest removing any terms that can indicate the presence of a tumor. You can try different text prompts, as well as changing the `vbeta` and `vvar` parameters which can have some influence on the final visual map.

If you have any other questions, let me know.

Best,
Taha

**Comment by TahaKoleilat** [comment]
Hi @pdx1028,

We have the full steps to prepare the datasets in the "Datasets" section in the README file. Download the datasets and prepare them in the same manner as shown [here](https://github.com/HealthX-Lab/MedCLIP-SAMv2/blob/8a3f7abe2f1c66c22c90faf9bd75d547ca73b698/README.md?plain=1#L42).

If you have any other questions, let me know.

Best,
Taha

**Comment by YeongHyeon** [comment]
Hi @TahaKoleilat 
Thank you for your kind support.
I'm still trying to change the saliency region by prompt changing.

It is true that the tumor region is more saliency than other regions even for the 'normal' state prompt.
Also, there is no problem with normal region segmentation. (that is definitely what I want)

So, this is a wonderful project that I met.
I will close this issue while sharing my latest trial.
Thank you!

<img width="400" alt="image" src="https://github.com/user-attachments/assets/0091e2cf-9c45-4e59-89f1-fe623044c8c8">
