### ISSUE TITLE
Data split

### ISSUE THREAD

**Issue by carloalbertobarbano** [HealthX-Lab/MedCLIP-SAMv2#3]
Hello, could you please provide the data split your used (train-val-test) for the datasets in Table 1 of the paper? 
Thank you

**Comment by carloalbertobarbano** [comment]
I am trying to replicate your experiments but the description of the data in the paper is different from the datasets listed. For example your paper says:  

> The Brain Tumor dataset [46],
comprising 1,462 T1-weighted MRI scans for training,
500 for validation, and 600 for testing.

but at the dataset page https://www.kaggle.com/datasets/ashkhagan/figshare-brain-tumor-dataset it says there are 3064 images. Can you please provide additional information?

**Comment by TahaKoleilat** [comment]
Hi @carloalbertobarbano,

Sorry for the late reply. I added [here](https://drive.google.com/file/d/1M3l91q96GZ9XPFYGbYhEiq3egGy6RfdZ/view?usp=sharing) all the datasets that we used. I will add a script soon in this [directory](https://github.com/HealthX-Lab/MedCLIP-SAMv2/tree/main/zeroshot_scripts) to reproduce the brain tumor results.

I will close this issue for now. In case you encounter any other issues, please feel free to reopen.
